### ISSUE TITLE
Feature request: mDNS: Add reverse lookup (IDFGH-7941)

### ISSUE THREAD

**Issue by hurricanefrog** [espressif/esp-protocols#101]
Currently, the mDNS component / library doesn't seem to support reverse lookup.

i.e. I get no reply to `dig -p 5353 -x <myip> @224.0.0.251`

Could this be added?

**Comment by david-cermak** [comment]
Yes, reverse lookup is currently not supported by the mDNS library. We are adding it to the road-map, but please understand that it doesn't have a very high priority, I expect the implementation to take place sometime in January.
