### ISSUE TITLE
BUG: The `ModuleIf` and `CommandableIf` do not define `virtual` destructors (IDFGH-6677)

### ISSUE THREAD

**Issue by b1ackviking** [espressif/esp-protocols#13]
In the following snippet, the `ModuleIf` abstract class defines an interface from which the `GenericModule` and other implementations derive. However, it does not define a `virtual` destructor. This is a bug that makes it impossible to destroy the derived object via a base class pointer.
https://github.com/espressif/esp-protocols/blob/5d27b2681a3c70c059cca3d274e04bee4791cbe0/components/esp_modem/include/cxx_include/esp_modem_types.hpp#L81-L98

Same for the `CommandableIf` abstract class.
https://github.com/espressif/esp-protocols/blob/5d27b2681a3c70c059cca3d274e04bee4791cbe0/components/esp_modem/include/cxx_include/esp_modem_types.hpp#L65-L79

**Comment by david-cermak** [comment]
Hi @b1ackviking 

Thanks for reporting this problem. This is a bug, yes, but I believe it is not so critical if objects were constructed by default or using the designated factories & builders:

https://github.com/espressif/esp-protocols/blob/5d27b2681a3c70c059cca3d274e04bee4791cbe0/components/esp_modem/include/cxx_include/esp_modem_dce_factory.hpp#L241-L246

They create the specific object only and don't rely on dynamic polymorphic delete on destruction.
If there was such an issue (memory leak or undefined behavior on delete), this should have been caught in the unit tests, for example here:
https://github.com/espressif/esp-protocols/blob/5d27b2681a3c70c059cca3d274e04bee4791cbe0/components/esp_modem/test/host_test/main/test_modem.cpp#L18 

This doesn't mean that this is not a recognized issue, of course if we create the device manually, such a test would fail:
```cpp
TEST_CASE("Test polymorphic delete", "[esp_modem]")
{
    auto term = std::make_unique<LoopbackTerm>(true);
    auto dte = std::make_shared<DTE>(std::move(term));
 
   esp_modem_dce_config_t dce_config = ESP_MODEM_DCE_DEFAULT_CONFIG("APN");
    GenericModule* device = new GenericModule(std::move(dte), &dce_config);
    device->power_down();
    delete device;
}
```

Thanks for posting the fix, I'll try to create new unit tests that exercise it and merge it.
