### ISSUE TITLE
Sync with other Repo (IDFGH-8196)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-protocols#130]
[https://github.com/espressif/esp-iot-solution/tree/usb/add_usb_solutions/examples/usb/host/usb_cdc_4g_module/components/esp_modem](https://github.com/espressif/esp-iot-solution/tree/usb/add_usb_solutions/examples/usb/host/usb_cdc_4g_module/components/esp_modem)

**Comment by david-cermak** [comment]
working on it, as mentioned in https://github.com/espressif/esp-protocols/issues/133#issuecomment-1240663036

**Comment by diplfranzhoepfinger** [comment]
very good !

**Comment by david-cermak** [comment]
Closing as USB DTE has been merged and published. (feel free to reopen if needed)
