### ISSUE TITLE
Strange Echo on SIM7070 (IDFGH-8499)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-protocols#159]

**Comment by diplfranzhoepfinger** [comment]
Normal: 

```

esp> cmd AT
I (14062) modem_console: Sending command AT with timeout 1000
I (14062) modem_console: AT
OK

esp> cmd AT
I (15232) modem_console: Sending command AT with timeout 1000
I (15242) modem_console: AT
OK

esp> cmd AT
I (16172) modem_console: Sending command AT with timeout 1000
I (16182) modem_console: AT
OK

esp> cmd AT
I (16982) modem_console: Sending command AT with timeout 1000
I (16992) modem_console: AT
OK

esp> cmd AT
I (17622) modem_console: Sending command AT with timeout 1000
I (17622) modem_console: AT
OK

esp> cmd AT
I (18332) modem_console: Sending command AT with timeout 1000
I (18342) modem_console: AT
OK

I (18992) modem_console: Sending command AT with timeout 1000
I (19002) modem_console: AT
OK

esp> cmd AT
I (19652) modem_console: Sending command AT with timeout 1000
I (19652) modem_console: AT
OK

esp> 
```

**Comment by diplfranzhoepfinger** [comment]
![](https://user-images.githubusercontent.com/37779037/195122826-9fa63162-1244-43cb-8411-3618175b3c77.png)

**Comment by diplfranzhoepfinger** [comment]
it seems like the Buffer is not processed one time ?

**Comment by diplfranzhoepfinger** [comment]
throw away the Data is wrong for sure. 

maybe the solution would be that "arbitrary Data" is collected by a Callback. 

OR: 

we have a option to say "we expect Number of \\r" like 5 or so for multiline respones ... 

i will think more about it.

**Comment by franz-ms-muc** [comment]
see here: 

![image](https://user-images.githubusercontent.com/69573151/195359775-8be4786d-39eb-44c5-bc3b-0f639dd3166d.png)


even with 30000000 timeout it immediately return after the OK, and then we see a Echo of the Sent command. ... 
shouldnt the RX and TX be seperate ?

**Comment by david-cermak** [comment]
> even with 30000000 timeout it immediately return after the OK, and then we see a Echo of the Sent command. ...

This console command looks for the `OK` by default, but you can supply your own pattern to check for:
```bash
esp>cmd AT+NETOPEN -p +NETOPEN:
```
(example for SIM7600 to open the network in command mode, this returns `OK` immediately and, after a couple of second the actual network status)
