### ISSUE TITLE
static functions (IDFGH-8694)

### ISSUE THREAD

**Issue by thiker5** [espressif/esp-protocols#174]
I just noticed that more functions has been set as static functions esp_modem_command_library.cpp. That will prevent reusability of esp_modem::dce_commands functions when a new device is added, for example:  generic_command, generic_get_string

**Comment by david-cermak** [comment]
Some of these statics have been already made public in 55c1223a1ee9ddecf588c42c55adceb4e3312363 (merged last week)

The problem with others is that they use `std::string_view` which is not available in c++11 and we'd like to keep the headers compatible (while using c++17 in implementation)
