### ISSUE TITLE
Does the websocket client support username/password? (IDFGH-9352)

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [espressif/esp-protocols#221]
I suspect that it doesnt, because ws_connect() doesnt do any of the http authentication header stuff.

esp_websocket_client_set_config() handles username and password correctly, but they are nowhere used ever.

I think this api design is a bit misleading from websocket_client?!

**Comment by david-cermak** [comment]
@0xFEEDC0DE64 Basic http authentication for ws-client is already in progress here https://github.com/espressif/esp-protocols/pull/215 (depends on an internal IDF MR, but that's going to be published soon)

As of now, you can check some workarounds, how this could be implemented via custom headers in few lines of code:
https://github.com/espressif/esp-idf/issues/8701#issuecomment-1092916687

**Comment by gabsuren** [comment]
@0xFEEDC0DE64 thank you for your question. The https://github.com/espressif/esp-protocols/pull/215 has been merge

**Comment by 0xFEEDC0DE64** [comment]
we tested it and it works, thank you
