### ISSUE TITLE
Using components of esp-protocols in custom component (IDFGH-9532)

### ISSUE THREAD

**Issue by cinargursoy** [espressif/esp-protocols#240]
Hello,

I'm writing a `components` library, and there is a component called `my_tcp_connection` which  is a `netif` wrapper over, GSM, ETH, WiFi connections. This component uses `esp-protocols` library.  Here is a part of the file tree and snippets from CMake files:

```
my_components
 ┣ my_tcp_connection
 ┃ ┣ inc
 ┃ ┃ ┗ my_tcp_connection.hpp
 ┃ ┣ test
 ┃ ┃ ┣ CMakeLists.txt
 ┃ ┃ ┣ component.mk
 ┃ ┃ ┗ test_my_tcp_connection.cpp
 ┃ ┗ CMakeLists.txt
 ┣ test_runner
 ┃ ┣ main
 ┃ ┃ ┣ CMakeLists.txt
 ┃ ┃ ┣ component.mk
 ┃ ┃ ┗ test_runner.c
 ┃ ┣ CMakeLists.txt
```

_test_runner/CMakeLists.txt_:
```
cmake_minimum_required(VERSION 3.5)

set(CMAKE_CXX_STANDARD 17)

set(EXTRA_COMPONENT_DIRS "../my_tcp_connection")
list(APPEND EXTRA_COMPONENT_DIRS "$ENV{ESP_PROTOCOLS}/components")

set(TEST_COMPONENTS "my_tcp_connection" CACHE STRING "List of components to test")

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(test_runner)
```

_my_tcp_connection/CMakeLists.txt_:
```
idf_component_register(
    INCLUDE_DIRS . inc
    REQUIRES esp_modem    
)
```
So this way it works, and builds. But what I want is to move `list(APPEND EXTRA_COMPONENT_DIRS "$ENV{ESP_PROTOCOLS}/components")` from _test_runner/CMakeLists.txt_ to _my_tcp_connection/CMakeLists.txt_ as `list(APPEND EXTRA_COMPONENT_DIRS "$ENV{ESP_PROTOCOLS}/components/esp_modem")`.

I can't do it just like that because:

> The set() commands should be placed after the cmake_minimum(...) line but before the include(...) line.

I don't want make client codes of `my_components` library, to `APPEND` `$ENV{ESP_PROTOCOLS}/components` to `EXTRA_COMPONENT_DIRS`. My opinion is, it has to be done in `component` itself, to abstract the client code from doing that.

How can I do that? Any other suggestion also would be helpful.

**Comment by david-cermak** [comment]
> My opinion is, it has to be done in component itself, to abstract the client code from doing that.

I agree that the component has to define their dependencies, and that's what you're doing in
```cmake
idf_component_register(
    INCLUDE_DIRS . inc
    REQUIRES *esp_modem*
)
```

The other thing is the search path for components (this is what's defined in `EXTRA_COMPONENT_DIRS`).  IMO it's still okay to defined it in your project makefile.

> How can I do that? Any other suggestion also would be helpful.

Have you tried adding a component manager dependency?
```
idf.py add-dependency "espressif/esp_modem^0.1.27"
```

I think you could even move the generated `idf_component.yml` to next to your *`my_transport`* component.

**Comment by david-cermak** [comment]
@cinargursoy Any other comment or question? Could we close it?

**Comment by cinargursoy** [comment]
Hi David,

Thanks for sharing your opinion;

>  IMO it's still okay to defined it in your project makefile.

I decided to continue this way.  Thanks for quick response, and the issue may  be closed.
