### ISSUE TITLE
I need an sim card insert and remove event when using bg96 and ppos lib which is used in esp-idf v 4.3 (IDFGH-9996)

### ISSUE THREAD

**Issue by radhikapatel15** [espressif/esp-protocols#281]
### Describe the solution you'd like.

I want the sim insert and remove events and also an event when modem fails for esp-idf v4.3

### Describe alternatives you've considered.

I have tried adding additional events to the modem events but that did not work

**Comment by david-cermak** [comment]
I think you get a *lost connection* event immediately after removing a SIM card.
So, as a workaround you can listen to already supported events and just check (with AT commands) if the card has or hasn't been removed/inserted.
The correct solution would probably be to listen to URC messages in the modem library, but that would need some work (and probably some customization) to make it universally working for most devices.

**Comment by radhikapatel15** [comment]
Thanks for your reply, But what u are saying will conflict when the server connection is also lost .
And for the workaround can share any sample code for it ? using bg96 and ppos lib for esp-idf v4.3?

**Comment by diplfranzhoepfinger** [comment]
ah, cool. i will try this !

**Comment by david-cermak** [comment]
Should be handled by an URC message, will be added in `v1.2.0`

**Comment by david-cermak** [comment]
URC handling has been merged in https://github.com/espressif/esp-protocols/pull/620

will be published as v1.2.0 in https://github.com/espressif/esp-protocols/pull/688
