### ISSUE TITLE
esp_modem does not compile anymore because of esp_modem_command_declare.inc (IDFGH-10005)

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [espressif/esp-protocols#284]
### Answers checklist.

- [X] I have read the documentation for [esp-protocols components](https://espressif.github.io/esp-protocols/) and the issue is not addressed there.
- [X] I have updated my esp-protocols branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Did I miss something?

```
In file included from <repo-dir>/esp-protocols/components/esp_modem/include/cxx_include/esp_modem_dce.hpp:11,                                     from <repo-dir>/esp-protocols/components/esp_modem/include/cxx_include/esp_modem_api.hpp:10,
                 from <repo-dir>/esp-protocols/components/esp_modem/src/esp_modem_api_target.cpp:12:
<repo-dir>/esp-protocols/components/esp_modem/include/cxx_include/esp_modem_dce_module.hpp:11:10: fatal error: generate/esp_modem
_command_declare.inc: No such file or directory                                                                                                              
   11 | #include "generate/esp_modem_command_declare.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     
compilation terminated.                                           
```

**Comment by gabsuren** [comment]
[0xFEEDC0DE64](https://github.com/0xFEEDC0DE64) thank you for the report. 
The issue should be fixed, please checkout the latest commit and try again
