### ISSUE TITLE
CMUX: Protocol mismatch: Missed trailing SOF, recovering... (IDFGH-10395)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-protocols#306]
### Answers checklist.

- [X] I have read the documentation for [esp-protocols components](https://espressif.github.io/esp-protocols/) and the issue is not addressed there.
- [X] I have updated my esp-protocols branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi, 

enabled 4-Wire Mode like this: 
https://github.com/diplfranzhoepfinger/esp-protocols-tree-master-components-esp_modem-examples-simple_cmux_client/commit/f4ae19e0faa4f6e1e6be943ce52befa24deeb66d

and getting this Error: 

`W (00:00:16.460) CMUX: Protocol mismatch: Missed trailing SOF, recovering...`

Full log: 
https://gist.github.com/diplfranzhoepfinger/6bb3857f499a1a37f381b264270c2505

Verbose Log here: 
https://gist.github.com/diplfranzhoepfinger/b1da771cd1d869d4adaa18bec943d444

**Comment by diplfranzhoepfinger** [comment]
I will make you a "verbose" Log later.

**Comment by diplfranzhoepfinger** [comment]
i added Verbose log above. 

@david-cermak

**Comment by diplfranzhoepfinger** [comment]
Hi, 

have advanced the Sample a bit: 

diplfranzhoepfinger/esp-protocols-tree-master-components-esp\_modem-examples-simple\_cmux\_client@d8f88b0

as the !7672 does not do Autobaud, we can do it the "old" way, 

and i tested and working. 

log here: 

https://gist.github.com/diplfranzhoepfinger/94ac7f9e94dbac07d93e71971766379f

**Comment by david-cermak** [comment]
@diplfranzhoepfinger Could we close this, too?

**Comment by david-cermak** [comment]
Closing, feel free to reopen
