### ISSUE TITLE
PPP session startup sequence 6-second delay (data race) (IDFGH-10455)

### ISSUE THREAD

**Issue by victorrar** [espressif/esp-protocols#308]
### Answers checklist.

- [X] I have read the documentation for [esp-protocols components](https://espressif.github.io/esp-protocols/) and the issue is not addressed there.
- [X] I have updated my esp-protocols branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I develop a sleepy application with a SIM7080g modem, and I found a strange 6-second delay during the establishment of a PPPoS session. 
(using CMUX, ESP-IDF v4.4.4, esp_modem v1.0.0 from the IDF component manager)

Later investigation showed that this is caused by: Netif invoking the data-send function before flags are updated.

This function is somehow executed during the startup action, but the flag is not set yet, and it returns an error:
https://github.com/espressif/esp-protocols/blob/68392f0ba9d4fd9c9c7fa1f7d54d0b3de53a1990/components/esp_modem/src/esp_modem_netif.cpp#LL34C10-L34C10

And the flag is set just right after the action is finished:
https://github.com/espressif/esp-protocols/blob/68392f0ba9d4fd9c9c7fa1f7d54d0b3de53a1990/components/esp_modem/src/esp_modem_netif.cpp#LL93C10-L93C10

Here is the log:
```
D (00:00:05.752) esp-netif_lwip-ppp: Phase Establish
D (00:00:05.757) event: running post NETIF_PPP_STATUS:262 with handler 0x400e0d20 and context 0x3ffc83a8 on loop 0x3ffbb8bc
D (00:00:05.757) lwip: pppos_send_config[1]: out_accm=FF FF FF FF

D (00:00:05.773) lwip: ppp_send_config[1]

D (00:00:05.779) event: running post NETIF_PPP_STATUS:262 with handler 0x400e8bb0 and context 0x3ffcb298 on loop 0x3ffbb8bc
D (00:00:05.783) lwip: pppos_recv_config[1]: in_accm=FF FF FF FF

D (00:00:05.800) lwip: ppp_recv_config[1]

D (00:00:05.807) lwip: ppp: auth protocols:
D (00:00:05.811) lwip:  PAP=0
D (00:00:05.813) lwip:  CHAP=0 CHAP_MD5=0
D (00:00:05.817) lwip:  CHAP_MS=0 CHAP_MS2=0
D (00:00:05.821) lwip: 

D (00:00:05.824) lwip: sent [LCP ConfReq id=0x1 <asyncmap 0x0> <magic 0x73d3bd17> <pcomp> <accomp>]

W (00:00:05.832) asd: esp_modem_dte_transmit 0 0x3ffcaed8
E (00:00:05.837) asd: goto failed2
E (00:00:05.841) asd: goto failed3
D (00:00:05.844) lwip: pppos_write[1]: output failed len=24

D (00:00:05.849) lwip: ppp_start[1]: finished

D (00:00:05.853) esp_netif_lwip: check: remote, if=0x3ffc6ab4 fn=0x400feb20

D (00:00:05.860) esp_netif_lwip: esp_netif_update_default_netif_lwip 0x3ffc6ab4
V (00:00:05.867) esp_netif_lwip: esp_netif_is_netif_up esp_netif:0x3ffc6ab4
D (00:00:05.874) esp_netif_lwip: call api in lwip: ret=0x0, give sem
D (00:00:05.887) event: running post OM_NETWORK_EVENT:0 with handler 0x400dc0ac and context 0x3ffc5864 on loop 0x3ffbb8bc

D (00:00:11.841) lwip: sent [LCP ConfReq id=0x1 <asyncmap 0x0> <magic 0x73d3bd17> <pcomp> <accomp>]

W (00:00:11.841) asd: esp_modem_dte_transmit 1 0x3ffcaed8
W (00:00:11.844) asd: Writing 47 bytes
W (00:00:11.847) asd: Writing to CMUX instance 0
V (00:00:11.852) Send: 0x3ffbb420   f9 05 ef 5f                                       |..._|
V (00:00:11.858) CMUX Received: 0x3ffcaf84   f9 05 ff 6d 7e ff                                 |...m~.|
V (00:00:11.860) Send: 0x3ffc5f54   7e ff 7d 23 c0 21 7d 21  7d 21 7d 20 7d 34 7d 22  |~.}#.!}!}!} }4}"|
D (00:00:11.870) CMUX: Payload frame: dlci:01 type:ff payload:54 available:2
V (00:00:11.878) Send: 0x3ffc5f64   7d 26 7d 20 7d 20 7d 20  7d 20 7d 25 7d 26 73 d3  |}&} } } } }%}&s.|
V (00:00:11.892) CMUX Received: 0x3ffcaf8a   7d 23 c0 21 7d 21 7d 23  7d 20 7d 39 7d 22 7d 26  |}#.!}!}#} }9}"}&|
V (00:00:11.894) Send: 0x3ffc5f74   bd 7d 37 7d 27 7d 22 7d  28 7d 22 7d 2b 3c 7e     |.}7}'}"}(}"}+<~|
V (00:00:11.910) CMUX Received: 0x3ffcaf9a   7d 20 7d 20 7d 20 7d 20  7d 23 7d 25 c2 23 7d 25  |} } } } }#}%.#}%|
V (00:00:11.913) Send: 0x3ffbb424   d0 f9                                             |..|
D (00:00:11.931) lwip: pppos_write[1]: len=24

``` 
The issue begins here:
`D (00:00:05.844) lwip: pppos_write[1]: output failed len=24`

I've inserted `ESP_LOGW("asd", "esp_modem_dte_transmit %d %p",ppp->signal.is_any(PPP_STARTED), ppp->ppp_dte.get());
` into the `esp_modem_dte_transmit`:
So, the log shows that It tries to write to DTE and calls `esp_modem_dte_transmit`, but `ppp->signal.is_any(PPP_STARTED)` is false and the function returns an error, causing LWIP to retransmit the message several seconds later. (5.8s and 11.8s timestamps give the exact 6-second delay I've measured)

Also, the issue can be confirmed if I set the signal before the `esp_netif_action_start` session is established without issues.

Changes:
```
void Netif::start()
{
    ppp_dte->set_read_cb([this](uint8_t *data, size_t len) -> bool {
        receive(data, len);
        return true;
    });
    signal.set(PPP_STARTED);
    esp_netif_action_start(driver.base.netif, nullptr, 0, nullptr);
}
```

And here is the new log:
```
D (00:00:05.760) esp-netif_lwip-ppp: Phase Establish
D (00:00:05.765) event: running post NETIF_PPP_STATUS:262 with handler 0x400e0d20 and context 0x3ffc83a8 on loop 0x3ffbb8bc
D (00:00:05.765) lwip: pppos_send_config[1]: out_accm=FF FF FF FF

D (00:00:05.782) lwip: ppp_send_config[1]

D (00:00:05.788) event: running post NETIF_PPP_STATUS:262 with handler 0x400e8bb0 and context 0x3ffcb298 on loop 0x3ffbb8bc
D (00:00:05.791) lwip: pppos_recv_config[1]: in_accm=FF FF FF FF

D (00:00:05.808) lwip: ppp_recv_config[1]

D (00:00:05.815) lwip: ppp: auth protocols:
D (00:00:05.819) lwip:  PAP=0
D (00:00:05.822) lwip:  CHAP=0 CHAP_MD5=0
D (00:00:05.825) lwip:  CHAP_MS=0 CHAP_MS2=0
D (00:00:05.829) lwip: 

D (00:00:05.833) lwip: sent [LCP ConfReq id=0x1 <asyncmap 0x0> <magic 0xfc6e0b> <pcomp> <accomp>]

W (00:00:05.841) asd: esp_modem_dte_transmit 1 0x3ffcaed8
W (00:00:05.846) asd: Writing 48 bytes
W (00:00:05.849) asd: Writing to CMUX instance 0
V (00:00:05.854) Send: 0x3ffbb370   f9 05 ef 61                                       |...a|
V (00:00:05.862) Send: 0x3ffcbac4   7e ff 7d 23 c0 21 7d 21  7d 21 7d 20 7d 34 7d 22  |~.}#.!}!}!} }4}"|
V (00:00:05.865) CMUX Received: 0x3ffcaf84   f9 05 ff 6d 7e ff 7d 23  c0 21 7d 21 7d 23 7d 20  |...m~.}#.!}!}#} |
V (00:00:05.871) Send: 0x3ffcbad4   7d 26 7d 20 7d 20 7d 20  7d 20 7d 25 7d 26 7d 20  |}&} } } } }%}&} |
V (00:00:05.882) CMUX Received: 0x3ffcaf94   7d 39 7d 22 7d 26 7d 20  7d 20 7d 20 7d 20 7d 23  |}9}"}&} } } } }#|
V (00:00:05.890) Send: 0x3ffcbae4   fc 6e 7d 2b 7d 27 7d 22  7d 28 7d 22 7d 3b ce 7e  |.n}+}'}"}(}"};.~|
V (00:00:05.909) Send: 0x3ffbb374   1e f9                                             |..|
V (00:00:05.910) CMUX Received: 0x3ffcafa4   7d 25 c2 23 7d 25 7d 25  7d 26 7d 32 49 d1 39 7d  |}%.#}%}%}&}2I.9}|
D (00:00:05.917) lwip: pppos_write[1]: len=24

D (00:00:05.931) lwip: ppp_start[1]: finished
```
So we can observe no delay before successful send, and further handshake continues instantly.

But, obviously, that is not a solution.

I haven't posted full logs because they're very verbose, so feel free to contact me anytime in case of additional information or testing is required. This delay seems small but may be critical in some applications, like my case.

Hope this will help fix the issue. Thank you in advance :)

**Comment by david-cermak** [comment]
Thank you for reporting this issue! You're correct, the PPPoS netif tries to establish connection immediately after starting (after calling `esp_netif_action_start()`).

> But, obviously, that is not a solution.

This could be the solution actually, as we should enable the physical layer first and then proceed with upper layers. Symmetrically to what we're doing on deinitialization (stop the upper layers and then disconnect):

https://github.com/espressif/esp-protocols/blob/68392f0ba9d4fd9c9c7fa1f7d54d0b3de53a1990/components/esp_modem/src/esp_modem_netif.cpp#L96-L100

I'll run some tests, but think we could go with this patch:
```patch
diff --git a/components/esp_modem/src/esp_modem_netif.cpp b/components/esp_modem/src/esp_modem_netif.cpp
index 75e271d..084b637 100644
--- a/components/esp_modem/src/esp_modem_netif.cpp
+++ b/components/esp_modem/src/esp_modem_netif.cpp
@@ -89,8 +89,8 @@ void Netif::start()
         receive(data, len);
         return true;
     });
-    esp_netif_action_start(driver.base.netif, nullptr, 0, nullptr);
     signal.set(PPP_STARTED);
+    esp_netif_action_start(driver.base.netif, nullptr, 0, nullptr);
 }
 
 void Netif::stop()
```

(note that we welcome contributions, so if you feel like it you can create a PR with this change)
