### ISSUE TITLE
testing new Modem modem-v1.0.3 on a SIMCOM A7672E with USB (IDFGH-11308)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-protocols#404]
Just check the examples.
This would create the corresponding DTE with these two terminals already included:

https://github.com/espressif/esp-protocols/blob/3e8de3af3a8bda2c1b0b1eb3e20c277fe123c40a/components/esp_modem/examples/pppos_client/main/pppos_client_main.c#L220-L222

The rest is the exactly same (one DTE, one DCE, one network interface).

---
PS: This constructs a DTE which simply takes two terminals, and sets the mode to `DUAL_MODE` so no further switching is necessary.

https://github.com/espressif/esp-protocols/blob/3e8de3af3a8bda2c1b0b1eb3e20c277fe123c40a/components/esp_modem/src/esp_modem_dte.cpp#L33-L36

_Originally posted by @david-cermak in https://github.com/espressif/esp-protocols/issues/375#issuecomment-1773086446_

so, made a github here: 
https://github.com/diplfranzhoepfinger/esp-protocols-tree-master-components-esp_modem-examples-pppos_client/tree/feature/USB-Modem

and a log here: 
https://gist.github.com/diplfranzhoepfinger/0a3c1c1921502d753910e54c7af1fdc7

strange thing: 
`AT+CSQ`

is replied by 

`+CSQ: 99,99`

but we get a

`E (22361) pppos_example: esp_modem_get_signal_quality failed with -1 ESP_FAIL`

**Comment by diplfranzhoepfinger** [comment]
@david-cermak 

here is my Ouput of 

  
[https://gist.github.com/diplfranzhoepfinger/8085a54f2320639e93eab6c43a846061](https://gist.github.com/diplfranzhoepfinger/8085a54f2320639e93eab6c43a846061)  
running this Code

[https://github.com/diplfranzhoepfinger/esp-protocols-tree-master-components-esp_modem-examples-pppos_client/tree/main/usb_host_lib](https://github.com/diplfranzhoepfinger/esp-protocols-tree-master-components-esp_modem-examples-pppos_client/tree/main/usb_host_lib)

**Comment by david-cermak** [comment]
@diplfranzhoepfinger Did you include the fix I mentioned in https://github.com/espressif/esp-protocols/issues/375#issuecomment-1772525793 ?

Just merged it yesterday; and added a new CI runner, which runs this example (S2+A7670E) https://github.com/espressif/esp-protocols/actions/runs/6628377154/job/18006092226#step:5:161 with this config:

https://github.com/espressif/esp-protocols/blob/2e6732882d813f7830fdc0604da49221b91a134d/components/esp_modem/examples/pppos_client/sdkconfig.ci.usb_a7670_s2#L3-L14

**Comment by franz-ms-muc** [comment]
this looks cool, i will try.

**Comment by diplfranzhoepfinger** [comment]
With your mentioned patch it works perfect in INFO Logging Mode: 

Gist with Logs: [https://gist.github.com/diplfranzhoepfinger/44aa433829e36bc7266f11f1e7fc5ab2](https://gist.github.com/diplfranzhoepfinger/44aa433829e36bc7266f11f1e7fc5ab2)

Repo with my Code: [https://github.com/diplfranzhoepfinger/esp-protocols-tree-master-components-esp_modem-examples-pppos_client/tree/v0.2](https://github.com/diplfranzhoepfinger/esp-protocols-tree-master-components-esp_modem-examples-pppos_client/tree/v0.2)

**Comment by david-cermak** [comment]
Good to hear that it works, closing then
