### ISSUE TITLE
ESP WebSocket Client does not pass-through keep-alive configuration to SSL transport (IDFGH-11457)

### ISSUE THREAD

**Issue by devanlai** [espressif/esp-protocols#430]
### Answers checklist.

- [X] I have read the documentation for esp-protocols [components](https://github.com/espressif/esp-protocols#readme) and the issue is not addressed there.
- [X] I have updated my esp-protocols branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

When configuring the ESP websocket client, it is not possible to configure or enable TCP keep-alive settings when using a TLS / wss scheme.

When specifying keep-alive parameters in `esp_websocket_client_config_t` for the underlying TCP connection, the configuration is not correctly passed through when using TLS.

By inspection of `esp_websocket_client_create_transport()`, I can see that the keep alive configuration is applied to the plaintext tcp connection via:
```c
if (client->keep_alive_cfg.keep_alive_enable) {
    esp_transport_tcp_set_keep_alive(tcp, &client->keep_alive_cfg);
}
```
but there is no corresponding call to:
```c
esp_transport_ssl_set_keep_alive(ssl, &client->keep_alive_cfg);
```

As a result, the ssl transport has no keep-alive configuration applied and it ignores any settings the user supplied to the websocket client.

Fixing this should be as simple as adding a call to `esp_transport_ssl_set_keep_alive()` for the SSL transport, similar to what's already done for the TCP transport.

**Comment by david-cermak** [comment]
@devanlai Thanks for the report. We've fixed it recently for the http-client in IDF [7c012e3f](https://github.com/espressif/esp-idf/commit/7c012e3fe1edaa1dd0a791c87cf5a3295bfd94e2), but seemingly missed the ws client.

will fix. 
(Note that we're open for PRs, if you feel like posting the change you described above)
