### ISSUE TITLE
esp_modem: get rid of fixed 10s Wait in pppos_client sample (IDFGH-11472)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-protocols#435]
### Answers checklist.

- [X] I have read the documentation for esp-protocols [components](https://github.com/espressif/esp-protocols#readme) and the issue is not addressed there.
- [X] I have updated my esp-protocols branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi, 

here:

**Comment by david-cermak** [comment]
@diplfranzhoepfinger you probably meant this:

https://github.com/espressif/esp-protocols/blob/0c6bb4bedc98a82947fea28afb537d6bcf587919/components/esp_modem/examples/pppos_client/main/pppos_client_main.c#L238-L239

We won't remove it, as this is an example that aims to demonstrates the nature of USB DTE, which can be freely removed, re-inserted and the example still works.
Of course the delay won't be needed in many applications, but it is useful to keep it in the example.
