### ISSUE TITLE
Timeout for setting PDP (AT+CGDCONT) in esp-modem is probably wrong? (IDFGH-11638)

### ISSUE THREAD

**Issue by huming2207** [espressif/esp-protocols#455]
### Answers checklist.

- [X] I have read the documentation for esp-protocols [components](https://github.com/espressif/esp-protocols#readme) and the issue is not addressed there.
- [X] I have updated my esp-protocols branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### What component are you using? If you choose Other, provide details in More Information.

esp_modem

### component version

82c2cf8936d4d363617825c3ed4028d1b0d20386

### IDF version.

v5.1.1-678-g8c6114d0d2

### More Information.

Hi there,

It seems like the `set_pdp_context()` call's timeout delay is way too long, see: https://github.com/espressif/esp-protocols/blob/master/components/esp_modem/src/esp_modem_command_library.cpp#L269

It supposed to be 300ms according to Quectel's AT manual, or 1 second for other modems:

<img width="970" alt="image" src="https://github.com/espressif/esp-protocols/assets/4463497/74e65445-9bc4-4f8d-adcc-6eec6e1f9442">

This may cause a hang for up to 150s. We have reproduced that for multiple times in the recent a few days. I guess if this times out in 300ms, the modem should be reset and start over the network registration again.

Regards,
Jackson

**Comment by david-cermak** [comment]
Thanks for reporting this and sorry for the inconvenience.
This is definitely wrong, I'll push a fix.

**Comment by huming2207** [comment]
@david-cermak great, thanks!

Meanwhile I've seen your pull request here: https://github.com/espressif/esp-protocols/pull/456/commits/aa5003c73bc0bf8da363117af672139b7fd95b33#diff-cb4f0037ddffd05f90dbe90c2a6b6469e5f33673fe100376fd0fc2d5258c5349R58

I guess the C++ API can be overloaded, instead of another function names `set_pdp_context_with_timeout()`?

Jackson

**Comment by huming2207** [comment]
@david-cermak thanks! The latest commit looks good!

**Comment by david-cermak** [comment]
Thanks for your suggestion on function overloads! I wasn't originally thinking of that as this is a part of the shared/generated API (as mentioned here https://github.com/espressif/esp-protocols/pull/456#discussion_r1431601188), but makes perfect sense and the fix look cleaner!

Thanks for helping with the review @huming2207 !
