### ISSUE TITLE
Broken link (IDFGH-11903)

### ISSUE THREAD

**Issue by pauljurczak** [espressif/esp-protocols#486]
### Answers checklist.

- [X] I have read the documentation for esp-protocols [components](https://github.com/espressif/esp-protocols#readme) and the issue is not addressed there.
- [X] I have updated my esp-protocols branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The link https://docs.espressif.com/projects/esp-protocols/docs/latest/esp_mqtt_cxx/index.html on https://github.com/espressif/esp-protocols/blob/master/components/esp_mqtt_cxx/README.md page is broken.

**Comment by euripedesrocha** [comment]
Hi @pauljurczak, thanks for reporting this. It will be fixed soon. 

In the meantime, you can find the documentation [here](https://docs.espressif.com/projects/esp-protocols/esp_mqtt_cxx/docs/latest/index.html)
