### ISSUE TITLE
FTP client to send and receive files (PACMAN-797) (IDFGH-12110)

### ISSUE THREAD

**Issue by chaabanemalki** [espressif/esp-protocols#510]
### Related area

Add FTP component

### Is your feature request related to a problem?

I would like to send files stored in file system and looking at the available libraries I don't seem to find an FTP client for that.

### Describe the solution you'd like

FTP client that uses native esp-idf component like TLS, sockets if applicable to send receive files

### I have checked existing list of Feature requests and I have provided enough information.

- [X] I confirm I have checked existing list of Feature requests and I have provided enough information.

**Comment by david-cermak** [comment]
Would the TFTP protocol serve your purpose? There'a simple TFTP server's implementation in lwip: https://github.com/espressif/esp-lwip/blob/2.1.3-esp/src/apps/tftp/tftp_server.c

**Comment by chaabanemalki** [comment]
Thank you @david-cermak for your feedback.

this seems to be the server part. I want to have the client part.
I found this repos https://github.com/nopnop2002/esp-idf-ftpClient 
Not sure how good it is. I guess I'll have to give it a try

**Comment by david-cermak** [comment]
We will not support an FTP client in `esp_protocols` for now. Although it seems useful, we do not see much common use-cases, while users could still use TFTP protocol (with server on the ESP32 side) suitable for minimalistic devices and embedded systems.
