### ISSUE TITLE
When using esp_modem components, cdc_acm: Incorrect number of bytes transferred error occasionally occurs after networking to the Internet (IDFGH-12227)

### ISSUE THREAD

**Issue by wishinlife** [espressif/esp-protocols#514]
### Answers checklist.

- [X] I have read the documentation for esp-protocols [components](https://github.com/espressif/esp-protocols#readme) and the issue is not addressed there.
- [X] I have updated my esp-protocols branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I'm based on ESP32S3, SIMCom A7670G and esp-idf v5.2 and I often get cdc_acm related errors when using esp_modem components for pppos surfing:
I (08:27:40.678) [Ping]: Ping addr 220.181.38.149 Restart...
E (08:27:40.680) cdc_acm: cdc_acm_host_data_tx_blocking(1194): Incorrect number of bytes transferred
E (08:27:40.684) ping_sock: send error=0
I (08:27:40.900) [Ping]: 64 bytes from 220.181.38.149 icmp_seq=1 ttl=50 time=211 ms
I (08:27:41.770) [Ping]: 64 bytes from 220.181.38.149 icmp_seq=2 ttl=50 time=91 ms

idf_component.yml：
  espressif/esp_modem: "^1.1.0"
  espressif/esp_modem_usb_dte:
    version: "^1.1.0~1"
    rules:
      - if: "idf_version >=4.4"
      - if: "target in [esp32s2, esp32s3]"

If data is not sent, but ppp LCP echo is enabled, this error occurs at an indefinite time, and sometimes it does not appear if data is sent afterward.How should I fix this?

**Comment by tore-espressif** [comment]
@wishinlife Thank you for the issue. Could you please provide some additional info?
* Does the network interface go down after this error?
* Do you see any lost packets during this error?
