### ISSUE TITLE
Kconfig in modem_example limits the UART pins till 31 - should be higher to support s3 (IDFGH-12700)

### ISSUE THREAD

**Issue by anujdeshpande** [espressif/esp-protocols#558]
### Answers checklist.

- [X] I have read the documentation for esp-protocols [components](https://github.com/espressif/esp-protocols#readme) and the issue is not addressed there.
- [X] I have updated my esp-protocols branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Working on getting elecrow's 7 inch RGB panel working with a ec200u modem. The pins for the UART connector are connected to IO 43/44.
The range should be higher than 31 (upto 48) in case you want to support esp32s3 as well, I think.

https://github.com/espressif/esp-protocols/blob/master/components/esp_modem/examples/modem_console/main/Kconfig.projbuild#L103

**Comment by david-cermak** [comment]
Hi Anuj!

Thanks for reporting this config issue! We should ideally source the env capabilities from IDF
```
    orsource "$IDF_PATH/examples/common_components/env_caps/$IDF_TARGET/Kconfig.env_caps"
```
and then use the `range ENV_GPIO_RANGE_MIN ENV_GPIO_OUT_RANGE_MAX`

will fix.
