### ISSUE TITLE
Memory usage esp_modem (IDFGH-7716)

### ISSUE THREAD

**Issue by wowaz** [espressif/esp-protocols#69]
Is it normal that the library uses 1,25 MB of ram?
I've tried to narrow it a bit down, but unfortunately wasn't able to find the source of the memory usage.

Once `esp_modem_new` is  added to the code the app uses at startup, even before executing `esp_modem_new`, 1,25MB more ram.
Without `esp_modem_new`: `heap_caps_get_free_size(MALLOC_CAP_DEFAULT)` = 4.367.500
With `esp_modem_new`: `heap_caps_get_free_size(MALLOC_CAP_DEFAULT)` = 3.056.596

  	void app_main(void)
	{
		ESP_LOGI("MAIN", "FREE HEAP CAPS: %zu", heap_caps_get_free_size(MALLOC_CAP_DEFAULT));

		esp_netif_config_t cfg = ESP_NETIF_DEFAULT_PPP();
		esp_netif = esp_netif_new(&cfg);
		if (esp_netif == NULL)
		  goto err;

		esp_modem_dte_config_t dte_config = ESP_MODEM_DTE_DEFAULT_CONFIG();
		dte_config.uart_config.rx_io_num = io_sim_rx;
		dte_config.uart_config.tx_io_num = io_sim_tx;
		dte_config.uart_config.cts_io_num = UART_PIN_NO_CHANGE;
		dte_config.uart_config.rts_io_num = UART_PIN_NO_CHANGE;
		dte_config.uart_config.baud_rate = 115200;
		dte_config.uart_config.port_num = UART_NUM_1;
		dte_config.uart_config.parity = UART_PARITY_DISABLE;
		dte_config.uart_config.stop_bits = UART_STOP_BITS_1;

		esp_modem_dce_config_t dce_config = ESP_MODEM_DCE_DEFAULT_CONFIG(settings_sim_apn);

		dce = esp_modem_new(&dte_config, &dce_config, esp_netif);
	}

I'm using ESP-IDF v4.2.3

**Comment by wowaz** [comment]
The patch for `v4.2.3` solved it for me. 
Probably a warning/info should be added to the documentation.
Thanks

**Comment by david-cermak** [comment]
@wowaz Thanks for the report and sorry for the delay. The fix has been merged to IDF `v4.2` release branch as https://github.com/espressif/esp-idf/commit/2bcfeb612fa90ac6d7d86675610cab217ab5287d
