### ISSUE TITLE
fix format warnings (IDFGH-7768)

### ISSUE THREAD

**Issue by Lapshin** [espressif/esp-protocols#79]
Related to https://github.com/espressif/esp-protocols/pull/73

TODO:

- [ ] Remove `-Wno-format` compiler option
- [ ] Fix all format warings

`esp_modem` is affected

**Comment by david-cermak** [comment]
Reopening as there're still some ` -Wno-format` used in the examples.

Need to fix `slip_custom_netif` and `esp_modem` (linux example), and remove the `mqtt` example

**Comment by david-cermak** [comment]
Closing as the examples mentioned above have been fix on master
