### ISSUE TITLE
AT+COPS? on Quectel BG96/BG95 (IDFGH-7770)

### ISSUE THREAD

**Issue by AshUK** [espressif/esp-protocols#80]
Reading the operator name using the `esp_modem_get_operator_name` with a BG95 and BG96 returns the following value.

`"Vodafone",9`

The modules have factory default configuration.

It is still very useful to know the access technology, preferred fix would ideally include this. e.g. `esp_modem_get_operator_name(esp_modem_dce_t *dce_wrap, char *p_name, int* act)`

Our current work around currently is to strip the double quotes and parse the act code.

```
	/* access technology */
	*p_act_out   = -1;
	char* p_last = strrchr(p_name, ',') + 1;
	if (p_last != NULL) {
		int act    = (int)strtol(p_last, NULL, 0);
		*p_act_out = act;
	}

	/* operator name */
	char operator_without_quotes[CELLULAR_OPERATOR_NAME_LENGTH] = {'\0'};
	ESP_LOGD(TAG, "name=%s", p_name);
	char* p_tmp = strtok(p_name, "\"");
	strncpy(operator_without_quotes, p_tmp, CELLULAR_OPERATOR_NAME_LENGTH);
	ESP_LOGD(TAG, "fixed name=%s", operator_without_quotes);
	strncpy(p_name, operator_without_quotes, CELLULAR_OPERATOR_NAME_LENGTH);
```

**Comment by david-cermak** [comment]
Thanks for the report! Have added in the linked PR, not sure about the C-API tho
